"use client";
import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Check, Loader2, Users, AlertCircle, CheckCircle2 } from "lucide-react";

type Client={id:string;name:string;assignedProgramId?:string|null};
type Program={id:string;name:string;durationWeeks:number;frequency:number};

export function BulkAssign(){
  const [clients,setClients]=useState<Client[]>([]);
  const [programs,setPrograms]=useState<Program[]>([]);
  const [selected,setSelected]=useState<string[]>([]);
  const [programId,setProgramId]=useState("");
  const [loading,setLoading]=useState(true);
  const [saving,setSaving]=useState(false);
  const [message,setMessage]=useState<string|null>(null);
  const [error,setError]=useState<string|null>(null);
  useEffect(()=>{let cancelled=false;Promise.all([fetch("/api/clients",{cache:"no-store"}),fetch("/api/programs",{cache:"no-store"})]).then(async([cr,pr])=>{const c=await cr.json();const p=await pr.json();if(!cr.ok)throw new Error(c?.error||"No se pudieron cargar los clientes.");if(!pr.ok)throw new Error(p?.error||"No se pudieron cargar los programas.");if(!cancelled){const clientsData=Array.isArray(c)?c:[];const programsData=Array.isArray(p)?p:[];setClients(clientsData);setPrograms(programsData);setSelected([]);setProgramId(programsData[0]?.id||"");}}).catch(e=>{if(!cancelled)setError(e instanceof Error?e.message:"No se pudo cargar la asignación.");}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[]);
  function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);setMessage(null);}
  async function assign(){if(!programId||selected.length===0)return;setSaving(true);setError(null);setMessage(null);const results=await Promise.allSettled(selected.map(id=>fetch(`/api/clients/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({assignedProgramId:programId})})));const failed=results.filter(r=>r.status==="fulfilled"&&!r.value.ok).length+results.filter(r=>r.status==="rejected").length;const done=selected.length-failed;if(done) {const assignedProgram=programs.find(p=>p.id===programId);setClients(prev=>prev.map(c=>selected.includes(c.id)?{...c,assignedProgramId:programId}:c));setMessage(`${done} cliente${done===1?"":"s"} actualizado${done===1?"":"s"} con ${assignedProgram?.name||"el programa seleccionado"}.`);setSelected([]);}if(failed)setError(`${failed} cliente${failed===1?"":"s"} no pudieron actualizarse.`);setSaving(false);}
  return <Card className="border-primary/20 bg-[#0B151E]"><CardHeader><CardTitle className="flex items-center gap-2"><Users size={16} className="text-primary"/> Asignación masiva</CardTitle><p className="text-xs text-[#8193A5]">Asigná un programa real a varios clientes de tu cartera en una sola acción.</p></CardHeader><CardContent className="space-y-3">{loading&&<div className="flex items-center justify-center gap-2 py-8 text-xs text-[#8193A5]"><Loader2 size={15} className="animate-spin"/> Cargando clientes y programas...</div>}{error&&<div role="alert" className="flex items-start gap-2 rounded-xl border border-red-500/20 bg-red-500/5 p-3 text-xs text-red-200"><AlertCircle size={14}/>{error}</div>}{message&&<div role="status" className="flex items-start gap-2 rounded-xl border border-primary/20 bg-primary/5 p-3 text-xs text-primary"><CheckCircle2 size={14}/>{message}</div>}{!loading&&<><div className="grid gap-2 max-h-80 overflow-y-auto pr-1">{clients.map(c=>{const sel=selected.includes(c.id);return <button key={c.id} type="button" onClick={()=>toggle(c.id)} className={`rounded-xl border p-2.5 flex items-center gap-2 text-left transition ${sel?"bg-primary text-black border-primary font-bold":"bg-[#081119] border-[#1C3142] text-white hover:border-primary/30"}`}><div className={`flex h-5 w-5 items-center justify-center rounded-full border-2 ${sel?"bg-black border-black text-primary":"border-zinc-700"}`}>{sel&&<Check size={12}/>}</div><span className="text-sm truncate">{c.name}</span>{c.assignedProgramId&&<span className="ml-auto text-[10px] text-zinc-500">asignado</span>}</button>})}{clients.length===0&&<p className="py-6 text-center text-xs text-[#8193A5]">No hay clientes en tu cartera.</p>}</div><select value={programId} onChange={e=>{setProgramId(e.target.value);setMessage(null)}} disabled={programs.length===0} className="h-11 w-full rounded-xl border border-[#1C3142] bg-[#081119] px-3 text-sm text-white outline-none focus:border-primary/40">{programs.map(p=><option key={p.id} value={p.id}>{p.name} · {p.durationWeeks} sem · {p.frequency}d/sem</option>)}{programs.length===0&&<option>Sin programas disponibles</option>}</select><Button variant="accent" className="w-full" disabled={saving||selected.length===0||!programId} onClick={()=>void assign()}>{saving?<><Loader2 size={14} className="animate-spin"/> Asignando...</>:selected.length?`Asignar a ${selected.length} cliente${selected.length===1?"":"s"} →`:"Seleccioná clientes"}</Button></>}</CardContent></Card>;
}
